version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "8888:8888"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    environment:
      - PORT=8888
  backend:
    build: backend
    ports:
     - "8889:8889"
    volumes:
      - ./backend:/code